services:
  ##############################################
  # PostgreSQL
  ##############################################
  postgres:
    image: postgres:15
    container_name: postgres-user-activity
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-activity
    ports:
      - "5432:5432"
    volumes:
      - pg_user_activity:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
  ##############################################
  # Redis (event stream)
  ##############################################
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_user_activity: